import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Dict, Any, Tuple

class ReportGenerator:
    def __init__(self, smtp_settings: Dict[str, Any]):
        """Initialize the ReportGenerator with SMTP settings"""
        self.smtp_settings = smtp_settings.copy()
        
        # Ensure port is an integer
        if isinstance(self.smtp_settings.get('port'), str):
            self.smtp_settings['port'] = int(self.smtp_settings['port'])
        
        self.email_template = '''
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap');
* {{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}}
body {{
    font-family: 'Inter', Arial, sans-serif;
    background: #f5f7fa;
    -webkit-font-smoothing: antialiased;
    line-height: 1.6;
    color: #2d3748;
}}
.container {{
    max-width: 600px;
    margin: 0 auto;
    padding: 20px;
}}
.logo-header {{
    text-align: center;
    padding: 25px 20px;
    background: linear-gradient(135deg, #ffffff 0%, #f8f9fa 100%);
    border-radius: 12px 12px 0 0;
    border-bottom: 2px solid #edf2f7;
}}
.logo-text {{
    font-size: 24px;
    font-weight: 600;
    color: #1a365d;
    margin-top: 10px;
}}
.card {{
    background: #ffffff;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.05);
    margin-bottom: 20px;
    overflow: hidden;
}}
.card-header {{
    background: linear-gradient(135deg, #007bff 0%, #0056b3 100%);
    color: #ffffff;
    padding: 15px 20px;
}}
.card-body {{
    padding: 20px;
    background: #ffffff;
}}
.metric {{
    background: #f8fafc;
    padding: 12px 15px;
    margin: 8px 0;
    border-radius: 6px;
    border-left: 4px solid #007bff;
}}
.issue {{
    background: #fff8f1;
    padding: 15px;
    margin: 10px 0;
    border-radius: 6px;
    border-left: 4px solid #ed8936;
}}
.summary {{
    background: #f7faff;
    padding: 15px;
    margin: 10px 0;
    border-radius: 6px;
}}
h2 {{
    margin: 0;
    font-size: 20px;
    font-weight: 600;
}}
h3 {{
    color: #2d3748;
    font-size: 16px;
    font-weight: 500;
    margin: 20px 0 10px 0;
}}
.footer {{
    text-align: center;
    padding: 20px;
    color: #718096;
    font-size: 13px;
    background: #f8f9fa;
    border-radius: 0 0 12px 12px;
    border-top: 2px solid #edf2f7;
}}
@media only screen and (max-width: 600px) {{
    .container {{
        padding: 10px;
    }}
    .card {{
        margin-bottom: 15px;
    }}
    .card-body {{
        padding: 15px;
    }}
}}
</style>
</head>
<body>
<div class="container">
    <div class="logo-header">
        <!-- Logo placeholder -->
        <div style="width:40px;height:40px;margin:0 auto;background:#007bff;border-radius:8px;"></div>
        <div class="logo-text">AutoTriage.AI</div>
    </div>
    <div style="background:#ffffff;border-radius:12px;box-shadow:0 4px 6px rgba(0,0,0,0.05);margin-top:-1px;">
        {content}
    </div>
    <div class="footer">
        This report was auto-generated by AutoTriage.AI
    </div>
</div>
</body>
</html>
'''

    def generate_ticket_report(self, ticket_data: Dict[str, Any]) -> str:
        """Generate HTML report from ticket data"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Build the basic report content
        content = [
            '<div class="card">',
            '<div class="card-header">',
            f'<h2>Incident Report - {ticket_data.get("ticket_id", "N/A")}</h2>',
            f'<div style="color:#e2e8f0;margin-top:5px;">{timestamp}</div>',
            '</div>',
            '<div class="card-body">',
            f'<div class="metric"><strong>Priority Level:</strong> {ticket_data.get("priority", "N/A")}</div>',
            f'<div class="metric"><strong>Confidence Score:</strong> {ticket_data.get("confidence", 0.0):.2f}</div>',
            f'<div class="metric"><strong>Assigned Team:</strong> {ticket_data.get("team", "N/A")}</div>',
            f'<div class="metric"><strong>Sentiment:</strong> {ticket_data.get("sentiment", "N/A").title()}</div>',
            '</div>',
            '</div>',
            '<div class="card">',
            '<div class="card-body">',
            '<h3>Issue Summary</h3>',
            f'<div class="summary">{ticket_data.get("summary", "Not available.")}</div>',
            '<h3>Extracted Issue</h3>',
            f'<div class="issue">{ticket_data.get("issue", "Not available.")}</div>',
            '</div>',
            '</div>',
            '<div class="card">',
            '<div class="card-body">',
            '<h3>Recommended Actions</h3>',
            f'<div class="summary">{ticket_data.get("suggested_solution", "No recommendations available.")}</div>',
            '</div>',
            '</div>'
        ]
        
        # Add admin comments if present
        if ticket_data.get('admin_comments'):
            content.extend([
                '<div class="card">',
                '<div class="card-body">',
                '<h3>Additional Comments</h3>',
                f'<div class="summary">{ticket_data["admin_comments"]}</div>',
                '</div>',
                '</div>'
            ])
        
        return self.email_template.format(content="\n".join(content))

    def send_report(self, recipient: str, subject: str, ticket_data: Dict[str, Any]) -> Tuple[bool, str]:
        """Send the report via email"""
        server = None
        try:
            # Validate SMTP settings
            required_settings = ['server', 'port', 'username', 'password']
            if not all(key in self.smtp_settings for key in required_settings):
                missing = [key for key in required_settings if key not in self.smtp_settings]
                error_msg = f"Missing SMTP settings: {', '.join(missing)}"
                print(f"Debug - {error_msg}")
                return False, error_msg

            # Prepare email message
            msg = MIMEMultipart('alternative')
            msg['Subject'] = subject
            msg['From'] = self.smtp_settings['username']
            msg['To'] = recipient
            
            # Generate and attach HTML report
            html_content = self.generate_ticket_report(ticket_data)
            msg.attach(MIMEText(html_content, 'html'))

            # Connect to SMTP server
            print(f"Debug - Connecting to SMTP server {self.smtp_settings['server']}:{self.smtp_settings['port']}...")
            server = smtplib.SMTP(self.smtp_settings['server'], self.smtp_settings['port'])
            server.set_debuglevel(1)  # Enable SMTP debug output
            
            # Initial EHLO
            server.ehlo()
            print("Debug - Initial EHLO completed")
            
            # Start TLS encryption
            print("Debug - Starting TLS...")
            server.starttls()
            
            # Re-run EHLO after TLS
            server.ehlo()
            print("Debug - TLS encryption established")
            
            # Login with credentials
            print(f"Debug - Attempting login for {self.smtp_settings['username']}...")
            server.login(
                self.smtp_settings['username'],
                self.smtp_settings['password'].strip()
            )
            print("Debug - Login successful")
            
            # Send email
            print("Debug - Sending message...")
            server.send_message(msg)
            print("Debug - Message sent successfully")
            
            # Clean up
            if server:
                server.quit()
            return True, "Email sent successfully"
            
        except smtplib.SMTPAuthenticationError as e:
            error_msg = "Authentication failed. Please verify your Gmail App Password. "
            error_msg += "Make sure you have:\n"
            error_msg += "1. Enabled 2-Step Verification in your Google Account\n"
            error_msg += "2. Generated an App Password specifically for this application\n"
            error_msg += "3. Copied the 16-character password correctly without spaces"
            print(f"Debug - Authentication Error: {str(e)}")
            return False, error_msg
            
        except smtplib.SMTPException as e:
            error_msg = f"SMTP error occurred: {str(e)}"
            print(f"Debug - SMTP Error: {str(e)}")
            return False, error_msg
            
        except Exception as e:
            error_msg = f"Unexpected error: {str(e)}"
            print(f"Debug - Unexpected Error: {str(e)}")
            import traceback
            traceback.print_exc()
            return False, error_msg
            
        finally:
            # Always try to clean up the connection
            if server:
                try:
                    server.quit()
                except Exception:
                    pass